#
# ~/.xinitrc
#

xrdb -merge "$DOTFILES/x11/Xresources"

if [ -f ~/.Xresources ]; then
    xrdb -merge ~/.Xresources
fi

# Use Mac layout
setxkbmap -variant mac

# Load custom keyboard map (remap left Alt to Ctrl)
xmodmap "$DOTFILES/x11/Xmodmap"

# Set keyboard repeat delay to 220 instead of default of 660
xset r rate 220

# Auto lock screen if all commands are available
command -v xautolock block scrot mogrify i3lock && xautolock -time 5 -locker block &

# Execute Compton if available
if command -v compton; then
    compton &
fi
# Execute Redshift if available
if command -v redshift; then
    redshift &
fi

# Window manager
exec i3

# vim: ft=sh
