[ids]
*

[main]
f5             = brightnessdown
f6             = brightnessup
f7             = sleep
f9             = touchpadtoggle
f10            = mute
f11            = volumedown
f12            = volumeup
brightnessdown = f5
brightnessup   = f6
sleep          = f7
touchpadtoggle = f9
mute           = f10
volumedown     = f11
volumeup       = f12
