#!/bin/sh -e

case "$BLOCK_BUTTON" in
  1) amixer -q set Master toggle ;;  # Left click toggle
  4) amixer -q set Master 1%+ ;; # Scroll up, increase
  5) amixer -q set Master 1%- ;; # Scroll down, decrease
esac

volume=$(amixer get Master | sed -n '/^ *\(Front Left\|Mono\):/{s/[^\[]*\[//;s/\].*//p}')
status=$(amixer get Master | sed -n '/^ *\(Front Left\|Mono\):/{s/.*\[//;s/\].*//p}')

echo "$volume"
echo "$volume"

if [ "off" = "$status" ]; then
    echo '#ffff00'
fi
