#!/bin/sh -e

cd $(dirname "$0")

cats=$(find . -mindepth 1 -maxdepth 1 -type d)

for cat in $cats; do
    cat=${cat#*/}

    if [ -f "$cat/map" ]; then
        files=$(cat "$cat/map")
    else
        files=$(find "$cat" -mindepth 1 -maxdepth 1 | awk -F/ '{$1=""; print substr($0, 2)}')
    fi

    echo "INSTALL_TARGETS += link-$cat"
    echo -n "link-$cat:"
    
    for file in $files; do
        echo -n " \$(DESTDIR)/$(echo -n $file)"
    done

    echo
    echo

    for file in $files; do
        echo "\$(DESTDIR)/$file: link/$cat/$file"
        echo -e '\tmkdir -p $$(dirname $@)'
        code='$$(python -c "import os; print(os.path.relpath('"'"'$(PWD)'"'"', '"'"'$$(dirname $@)'"'"'))")'
        echo -e "\tln -fs $code/\$< \$@"
        echo
    done
done
