#
# ~/.zshrc
#

# Initialization {{{
# ==================

    export ZSH=$DOTFILES/deps/zsh/oh-my-zsh

    # Theme
    # ZSH_THEME=robbyrussell

    # Do not auto update `oh-my-zsh` (performance)
    DISABLE_AUTO_UPDATE=true

    # No title in tmux
    if [ -n "$TMUX" ]; then
        DISABLE_AUTO_TITLE=true
    fi

    # Don't mark untracked files as dirty (performance)
    DISABLE_UNTRACKED_FILES_DIRTY=true

    # Custom `oh-my-zsh` directory
    # ZSH_CUSTOM=$DOTFILES/src/zsh

    # # Enabled plugins
    # plugins=(
    #     git
    #     colored-man-pages
    #     history-substring-search
    #     zsh-syntax-highlighting
    # )

    # Load core
    # source "$ZSH/oh-my-zsh.sh"

    autoload -U compinit

    compinit -d ~/.zcompdump

    # Load only what I want from `oh-my-zsh`
    source "$ZSH/lib/clipboard.zsh"
    source "$ZSH/lib/compfix.zsh"
    source "$ZSH/lib/completion.zsh"
    source "$ZSH/lib/correction.zsh"
    source "$ZSH/lib/directories.zsh"
    source "$ZSH/lib/git.zsh"
    source "$ZSH/lib/grep.zsh"
    source "$ZSH/lib/history.zsh"
    source "$ZSH/lib/key-bindings.zsh"
    source "$ZSH/lib/theme-and-appearance.zsh"

    # Theme
    source "$ZSH/themes/robbyrussell.zsh-theme"

    # Plugins
    source "$ZSH/plugins/git/git.plugin.zsh"
    source "$ZSH/plugins/colored-man-pages/colored-man-pages.plugin.zsh"
    source "$ZSH/plugins/history-substring-search/history-substring-search.plugin.zsh"
    source "$DOTFILES/deps/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh"

# }}}

# Essentials {{{
# ==============

    # Allow adding comments in interactive session
    setopt interactivecomments

# }}}

# Theme {{{

    # Terminal colors (except in tmux)
    if [ -z "$TMUX" ]; then
        source $DOTFILES/deps/shell/base16-shell/scripts/base16-default-dark.sh
    fi

    # Apply `LS_COLORS` to completion
    zstyle ':completion:*:default' list-colors "${(s.:.)LS_COLORS}"

# }}}

# Aliases {{{
# ===========

    # Shortcuts
    alias l=ll
    alias q=exit

    # Globbing move command
    autoload zmv
    alias mmv='noglob zmv -W'

    # Get remote IP from CodeJam (at home)
    alias ipc='curl ip.codejam.info'

    # Get remote IP from Deblan (can't use home server when in LAN)
    alias ipd='curl ip.deblan.org && echo'

# }}}
