#
# ~/.config/zsh/zshrc
#
# See zshbuiltins(1) for zsh commands documentation.
# See zshoptions(1) for options documentation.
#

# Source dotfiles' config files
for file in "$DOTFILES"/src/zsh/zshrc.d/*.zsh; do
    . "$file"
done

# Source local config files if any
if [ -d ~/.config/zsh/zshrc.d ]; then
    for file in ~/.config/zsh/zshrc.d/*.zsh; do
        . "$file"
    done
fi

#
# Prevent the previous command to propagate an error in `$?`
# by executing something that will not fail (typically the NOP command).
#
:
