#
# ~/.zshenv
#

# See details in `zshrc`
if [[ "$OSTYPE" = darwin* ]] && ! [ -n "$IN_ZSHRC" ]; then
    return
fi

#
# Deduplicate `PATH` entries.
#
# When starting X through a TTY, the environment will be loaded once already,
# so when we open a new terminal, this file is sourced again and we'll
# duplicate everything.
#
# Or even when using a login manager, I like those paths to be available to
# programs in the graphical session so I also source this file in
# `~/.xprofile` and we end up with the the same duplication in terminals.
#
typeset -U PATH

PATH=$PATH:~/.local/bin # Local bin
PATH=$PATH:$DOTFILES/bin/shared # Dotfiles' bin (all systems)
PATH=$PATH:~/bin # User bin
export PATH

export EDITOR=vim
export PAGER=less

if [ "$TERM" = xterm-ghostty ]; then
    #
    # Keep until `xterm-ghostty` is supported broadly.
    # For now this makes nested Zsh sessions work through SSH, as well as
    # control sequences forwarding to Vim.
    #
    export TERM=xterm-256color
fi
