#
# ~/.zshenv
#

#
# Deduplicate `PATH` entries.
#
# When starting X through a TTY, the environment will be loaded once already,
# so when we open a new terminal, this file is sourced again and we'll
# duplicate everything.
#
# Or even when using a login manager, I like those paths to be available to
# programs in the graphical session so I also source this file in
# `~/.xprofile` and we end up with the the same duplication in terminals.
#
typeset -U PATH

PATH=~/.local/bin:$PATH # Local bin
PATH=$DOTFILES/bin/common:$PATH # Dotfiles' bin (all systems)
PATH=~/bin:$PATH # User bin
export PATH

export EDITOR=vim
export PAGER=less

export ERL_AFLAGS='-kernel shell_history enabled' # Keep history in IEx
