#!/bin/sh -e

main() {
    echo
    echo "Copying $1 to $2"

    # The destination already exists
    if [ -f "$2" ]; then
        if [ -h "$2" ]; then
            # It's a symlink
            echo "$2 is a symlink to $(readlink "$2")"
        else
            # Get the diff, stop if same content
            if diff=$(git --no-pager diff "$2" "$1"); then
                return
            fi

            echo "$2 already exists"
            echo
            echo "$diff"
        fi
    fi

    # Remove maybe existing destination
    rm -f "$2"

    cp -i "$1" "$2"
}

. $(dirname "$0")/args.sh
