#!/bin/sh -e

relpath() {
    python -c 'import os, sys; print(os.path.relpath(sys.argv[1], sys.argv[2]))' "$1" "$2"
}

main() {
    # Link target (relative)
    local target="$(relpath "$1" "$(dirname "$2")")"

    # Old link target
    local old="$(readlink "$2")"

    echo
    echo "Linking $2 to $1"

    # The destination is a link
    if [ -h "$2" ]; then
        # Target have not changed
        if [ "$old" = "$target" ]; then
            return
        fi

        echo "$2 already links to $old"
    elif [ -f "$2" ]; then
        echo "$2 is a file"
        echo
        git --no-pager diff "$2" "$1" || true
    fi

    ln -sfin "$target" "$2"
}

. $(dirname "$0")/args.sh
