#!/bin/sh -e

relpath() {
    python -c 'import os, sys; print(os.path.relpath(sys.argv[1], sys.argv[2]))' "$1" "$2"
}

main() {
    # Destination file
    local dest="$(relpath "$1" "$(dirname "$2")")"

    # Old link target
    local old="$(readlink "$2")"

    echo
    echo "Linking $2 to $dest"

    # The destination is a link
    if [ -h "$2" ]; then
        # Target have not changed
        if [ "$old" = "$dest" ]; then
            return
        fi

        echo "$2 already links to $old"
    elif [ -f "$2" ]; then
        echo "$2 is a file"
        echo
        git --no-pager diff "$2" "$dest"
    fi

    ln -sfi --no-dereference "$dest" "$2"
}

. $(dirname "$0")/args.sh
