"
" ~/.config/vim/gvimrc
"

" GUI stuff
" =========

set guioptions-=m " Remove menu bar
set guioptions-=T " Remove toolbar
set guioptions-=r " Remove right scroll bar
set guioptions-=L " Remove left scroll bar
