#!/bin/sh -e

cd "$(dirname "$0")"
plugins=$PWD/plugins.sh
command=$1

mkdir -vp ~/.vim/plugins
cd ~/.vim/plugins

git_install() {
    if [ ! -d "$2" ]; then
        echo "Cloning $1 into $2"
        command git clone -q "$1" "$2"
    fi
}

git_update() {
    if [ -d "$2" ]; then
        echo "Pulling $2"
        command git -C "$2" remote set-url origin "$1"
        command git -C "$2" pull
    else
        git_install "$@"
    fi
}

git_gen() {
    echo "set runtimepath^=~/.vim/plugins/$2"
}

git() {
    "git_$command" "$1" "$(basename -s .git "$1")"
}

gh() {
    git "https://github.com/$1.git"
}

source "$plugins"

wait
